# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCalendarWidget, QCheckBox,
    QDockWidget, QFormLayout, QFrame, QGridLayout,
    QHBoxLayout, QHeaderView, QLabel, QLayout,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QProgressBar, QPushButton, QRadioButton, QSizePolicy,
    QSlider, QStatusBar, QTextBrowser, QTreeView,
    QVBoxLayout, QWidget)

from CustomWidgets import (Custom_Button, Custom_ComboBox, Custom_LineEdit, Custom_widget,
    Custum_Label)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1470, 864)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QSize(1800, 960))
        font = QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QMainWindow.AllowNestedDocks|QMainWindow.AllowTabbedDocks|QMainWindow.AnimatedDocks)
        self.actionFile_F = QAction(MainWindow)
        self.actionFile_F.setObjectName(u"actionFile_F")
        self.action_Save = QAction(MainWindow)
        self.action_Save.setObjectName(u"action_Save")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QSize(30, 30))
        self.horizontalLayout_4 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setSizeConstraint(QLayout.SetMinimumSize)
        self.sheetImage_Label = Custum_Label(self.centralwidget)
        self.sheetImage_Label.setObjectName(u"sheetImage_Label")
        sizePolicy1 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.sheetImage_Label.sizePolicy().hasHeightForWidth())
        self.sheetImage_Label.setSizePolicy(sizePolicy1)
        self.sheetImage_Label.setMinimumSize(QSize(1, 1))
        self.sheetImage_Label.setBaseSize(QSize(670, 900))
        self.sheetImage_Label.setFrameShape(QFrame.NoFrame)
        self.sheetImage_Label.setLineWidth(0)
        self.sheetImage_Label.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_4.addWidget(self.sheetImage_Label)

        MainWindow.setCentralWidget(self.centralwidget)
        self.fileList_DockWidget = QDockWidget(MainWindow)
        self.fileList_DockWidget.setObjectName(u"fileList_DockWidget")
        self.fileList_DockWidget.setMinimumSize(QSize(210, 476))
        self.fileList_DockWidget.setFont(font)
        self.fileList_DockWidget.setFocusPolicy(Qt.ClickFocus)
        self.fileList_DockWidget.setFloating(False)
        self.fileList_DockWidgetContents = QWidget()
        self.fileList_DockWidgetContents.setObjectName(u"fileList_DockWidgetContents")
        self.verticalLayout_2 = QVBoxLayout(self.fileList_DockWidgetContents)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 3)
        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setSizeConstraint(QLayout.SetMinimumSize)
        self.file_TreeView = QTreeView(self.fileList_DockWidgetContents)
        self.file_TreeView.setObjectName(u"file_TreeView")
        self.file_TreeView.setMinimumSize(QSize(0, 0))
        self.file_TreeView.setMaximumSize(QSize(16777215, 16777215))
        font1 = QFont()
        font1.setPointSize(11)
        self.file_TreeView.setFont(font1)
        self.file_TreeView.setFocusPolicy(Qt.ClickFocus)
        self.file_TreeView.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.file_TreeView.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.file_TreeView.setAutoExpandDelay(0)
        self.file_TreeView.setIndentation(10)
        self.file_TreeView.setSortingEnabled(True)
        self.file_TreeView.setAllColumnsShowFocus(True)

        self.verticalLayout_4.addWidget(self.file_TreeView)

        self.directory_LineEdit = QLineEdit(self.fileList_DockWidgetContents)
        self.directory_LineEdit.setObjectName(u"directory_LineEdit")
        self.directory_LineEdit.setFont(font1)
        self.directory_LineEdit.setFocusPolicy(Qt.ClickFocus)

        self.verticalLayout_4.addWidget(self.directory_LineEdit)

        self.folderSelect_Button = Custom_Button(self.fileList_DockWidgetContents)
        self.folderSelect_Button.setObjectName(u"folderSelect_Button")
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.folderSelect_Button.sizePolicy().hasHeightForWidth())
        self.folderSelect_Button.setSizePolicy(sizePolicy2)
        self.folderSelect_Button.setMinimumSize(QSize(0, 28))
        self.folderSelect_Button.setMaximumSize(QSize(16777215, 16777215))
        self.folderSelect_Button.setFocusPolicy(Qt.ClickFocus)

        self.verticalLayout_4.addWidget(self.folderSelect_Button)

        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SetFixedSize)
        self.deleteFile_Button = Custom_Button(self.fileList_DockWidgetContents)
        self.deleteFile_Button.setObjectName(u"deleteFile_Button")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.deleteFile_Button.sizePolicy().hasHeightForWidth())
        self.deleteFile_Button.setSizePolicy(sizePolicy3)
        self.deleteFile_Button.setMinimumSize(QSize(0, 28))
        self.deleteFile_Button.setMaximumSize(QSize(16777215, 16777215))
        self.deleteFile_Button.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout.addWidget(self.deleteFile_Button, 2, 0, 1, 1)

        self.makeCSV_Button = Custom_Button(self.fileList_DockWidgetContents)
        self.makeCSV_Button.setObjectName(u"makeCSV_Button")
        sizePolicy3.setHeightForWidth(self.makeCSV_Button.sizePolicy().hasHeightForWidth())
        self.makeCSV_Button.setSizePolicy(sizePolicy3)
        self.makeCSV_Button.setMinimumSize(QSize(0, 28))
        self.makeCSV_Button.setMaximumSize(QSize(16777215, 16777215))
        self.makeCSV_Button.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout.addWidget(self.makeCSV_Button, 2, 1, 1, 1)

        self.prevSheet_Button = Custom_Button(self.fileList_DockWidgetContents)
        self.prevSheet_Button.setObjectName(u"prevSheet_Button")
        self.prevSheet_Button.setMinimumSize(QSize(100, 30))
        self.prevSheet_Button.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout.addWidget(self.prevSheet_Button, 0, 0, 1, 1)

        self.nextSheet_Button = Custom_Button(self.fileList_DockWidgetContents)
        self.nextSheet_Button.setObjectName(u"nextSheet_Button")
        sizePolicy3.setHeightForWidth(self.nextSheet_Button.sizePolicy().hasHeightForWidth())
        self.nextSheet_Button.setSizePolicy(sizePolicy3)
        self.nextSheet_Button.setMinimumSize(QSize(100, 30))
        self.nextSheet_Button.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout.addWidget(self.nextSheet_Button, 0, 1, 1, 1)

        self.gridLayout.setColumnMinimumWidth(0, 50)
        self.gridLayout.setColumnMinimumWidth(1, 50)

        self.verticalLayout_4.addLayout(self.gridLayout)


        self.verticalLayout_2.addLayout(self.verticalLayout_4)

        self.fileList_DockWidget.setWidget(self.fileList_DockWidgetContents)
        MainWindow.addDockWidget(Qt.LeftDockWidgetArea, self.fileList_DockWidget)
        self.receiptImage_DockWidget = Custom_widget(MainWindow)
        self.receiptImage_DockWidget.setObjectName(u"receiptImage_DockWidget")
        sizePolicy.setHeightForWidth(self.receiptImage_DockWidget.sizePolicy().hasHeightForWidth())
        self.receiptImage_DockWidget.setSizePolicy(sizePolicy)
        self.receiptImage_DockWidget.setFont(font)
        self.receiptImage_DockWidget.setFocusPolicy(Qt.ClickFocus)
        self.receiptImage_DockWidget.setFloating(False)
        self.receiptImage_DockWidget.setAllowedAreas(Qt.AllDockWidgetAreas)
        self.receiptImage_DockWidgetContents = QWidget()
        self.receiptImage_DockWidgetContents.setObjectName(u"receiptImage_DockWidgetContents")
        sizePolicy.setHeightForWidth(self.receiptImage_DockWidgetContents.sizePolicy().hasHeightForWidth())
        self.receiptImage_DockWidgetContents.setSizePolicy(sizePolicy)
        self.receiptImage_DockWidgetContents.setMinimumSize(QSize(30, 30))
        self.verticalLayout = QVBoxLayout(self.receiptImage_DockWidgetContents)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setSizeConstraint(QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.receiptImage_Label = QLabel(self.receiptImage_DockWidgetContents)
        self.receiptImage_Label.setObjectName(u"receiptImage_Label")
        sizePolicy.setHeightForWidth(self.receiptImage_Label.sizePolicy().hasHeightForWidth())
        self.receiptImage_Label.setSizePolicy(sizePolicy)
        self.receiptImage_Label.setMinimumSize(QSize(250, 12))
        self.receiptImage_Label.setMaximumSize(QSize(16777215, 16777215))
        self.receiptImage_Label.setFocusPolicy(Qt.ClickFocus)
        self.receiptImage_Label.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)

        self.verticalLayout.addWidget(self.receiptImage_Label)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, -1)
        self.prevReceipt_Button = QPushButton(self.receiptImage_DockWidgetContents)
        self.prevReceipt_Button.setObjectName(u"prevReceipt_Button")
        self.prevReceipt_Button.setFocusPolicy(Qt.ClickFocus)

        self.horizontalLayout_3.addWidget(self.prevReceipt_Button)

        self.reOcr_Button = QPushButton(self.receiptImage_DockWidgetContents)
        self.reOcr_Button.setObjectName(u"reOcr_Button")
        self.reOcr_Button.setFocusPolicy(Qt.ClickFocus)

        self.horizontalLayout_3.addWidget(self.reOcr_Button)

        self.nextReceipt_Button = QPushButton(self.receiptImage_DockWidgetContents)
        self.nextReceipt_Button.setObjectName(u"nextReceipt_Button")
        self.nextReceipt_Button.setFocusPolicy(Qt.ClickFocus)

        self.horizontalLayout_3.addWidget(self.nextReceipt_Button)


        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.receiptImage_DockWidget.setWidget(self.receiptImage_DockWidgetContents)
        MainWindow.addDockWidget(Qt.RightDockWidgetArea, self.receiptImage_DockWidget)
        self.sheetProcess_DockWidget = QDockWidget(MainWindow)
        self.sheetProcess_DockWidget.setObjectName(u"sheetProcess_DockWidget")
        sizePolicy.setHeightForWidth(self.sheetProcess_DockWidget.sizePolicy().hasHeightForWidth())
        self.sheetProcess_DockWidget.setSizePolicy(sizePolicy)
        self.sheetProcess_DockWidget.setMinimumSize(QSize(670, 128))
        self.sheetProcess_DockWidget.setMaximumSize(QSize(524287, 128))
        self.sheetProcess_DockWidget.setFont(font)
        self.sheetProcess_DockWidget.setFocusPolicy(Qt.ClickFocus)
        self.sheetProcess_DockWidget.setAllowedAreas(Qt.AllDockWidgetAreas)
        self.sheetProcess_DockWidgetContents = QWidget()
        self.sheetProcess_DockWidgetContents.setObjectName(u"sheetProcess_DockWidgetContents")
        self.horizontalLayout_2 = QHBoxLayout(self.sheetProcess_DockWidgetContents)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.sheetProcess_QVBoxLayout = QVBoxLayout()
        self.sheetProcess_QVBoxLayout.setSpacing(0)
        self.sheetProcess_QVBoxLayout.setObjectName(u"sheetProcess_QVBoxLayout")
        self.standerd_Button = Custom_Button(self.sheetProcess_DockWidgetContents)
        self.standerd_Button.setObjectName(u"standerd_Button")
        self.standerd_Button.setMinimumSize(QSize(0, 30))
        self.standerd_Button.setFocusPolicy(Qt.ClickFocus)

        self.sheetProcess_QVBoxLayout.addWidget(self.standerd_Button)

        self.mideum_Button = Custom_Button(self.sheetProcess_DockWidgetContents)
        self.mideum_Button.setObjectName(u"mideum_Button")
        self.mideum_Button.setMinimumSize(QSize(0, 30))
        self.mideum_Button.setFocusPolicy(Qt.ClickFocus)

        self.sheetProcess_QVBoxLayout.addWidget(self.mideum_Button)

        self.lite_Button = Custom_Button(self.sheetProcess_DockWidgetContents)
        self.lite_Button.setObjectName(u"lite_Button")
        self.lite_Button.setMinimumSize(QSize(0, 30))
        self.lite_Button.setFocusPolicy(Qt.ClickFocus)

        self.sheetProcess_QVBoxLayout.addWidget(self.lite_Button)


        self.horizontalLayout_2.addLayout(self.sheetProcess_QVBoxLayout)

        self.horizontalLayout_11 = QHBoxLayout()
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_11.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.sliders_QVBoxLayout = QVBoxLayout()
        self.sliders_QVBoxLayout.setObjectName(u"sliders_QVBoxLayout")
        self.sliders_QVBoxLayout.setSizeConstraint(QLayout.SetNoConstraint)
        self.value1_Label = QLabel(self.sheetProcess_DockWidgetContents)
        self.value1_Label.setObjectName(u"value1_Label")
        sizePolicy4 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.value1_Label.sizePolicy().hasHeightForWidth())
        self.value1_Label.setSizePolicy(sizePolicy4)
        self.value1_Label.setFocusPolicy(Qt.ClickFocus)

        self.sliders_QVBoxLayout.addWidget(self.value1_Label)

        self.value1_Slider = QSlider(self.sheetProcess_DockWidgetContents)
        self.value1_Slider.setObjectName(u"value1_Slider")
        sizePolicy3.setHeightForWidth(self.value1_Slider.sizePolicy().hasHeightForWidth())
        self.value1_Slider.setSizePolicy(sizePolicy3)
        self.value1_Slider.setMaximumSize(QSize(5242, 5242))
        self.value1_Slider.setFocusPolicy(Qt.ClickFocus)
        self.value1_Slider.setMaximum(255)
        self.value1_Slider.setOrientation(Qt.Horizontal)

        self.sliders_QVBoxLayout.addWidget(self.value1_Slider)

        self.value2_Label = QLabel(self.sheetProcess_DockWidgetContents)
        self.value2_Label.setObjectName(u"value2_Label")
        sizePolicy5 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Minimum)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.value2_Label.sizePolicy().hasHeightForWidth())
        self.value2_Label.setSizePolicy(sizePolicy5)
        self.value2_Label.setFocusPolicy(Qt.ClickFocus)
        self.value2_Label.setOpenExternalLinks(False)
        self.value2_Label.setTextInteractionFlags(Qt.LinksAccessibleByMouse)

        self.sliders_QVBoxLayout.addWidget(self.value2_Label)

        self.value2_Slider = QSlider(self.sheetProcess_DockWidgetContents)
        self.value2_Slider.setObjectName(u"value2_Slider")
        sizePolicy3.setHeightForWidth(self.value2_Slider.sizePolicy().hasHeightForWidth())
        self.value2_Slider.setSizePolicy(sizePolicy3)
        self.value2_Slider.setMaximumSize(QSize(5242, 5242))
        self.value2_Slider.setFocusPolicy(Qt.ClickFocus)
        self.value2_Slider.setMaximum(255)
        self.value2_Slider.setOrientation(Qt.Horizontal)

        self.sliders_QVBoxLayout.addWidget(self.value2_Slider)

        self.value3_Label = QLabel(self.sheetProcess_DockWidgetContents)
        self.value3_Label.setObjectName(u"value3_Label")
        sizePolicy5.setHeightForWidth(self.value3_Label.sizePolicy().hasHeightForWidth())
        self.value3_Label.setSizePolicy(sizePolicy5)
        self.value3_Label.setFocusPolicy(Qt.ClickFocus)
        self.value3_Label.setOpenExternalLinks(False)
        self.value3_Label.setTextInteractionFlags(Qt.LinksAccessibleByMouse)

        self.sliders_QVBoxLayout.addWidget(self.value3_Label)

        self.value3_Slider = QSlider(self.sheetProcess_DockWidgetContents)
        self.value3_Slider.setObjectName(u"value3_Slider")
        sizePolicy3.setHeightForWidth(self.value3_Slider.sizePolicy().hasHeightForWidth())
        self.value3_Slider.setSizePolicy(sizePolicy3)
        self.value3_Slider.setMaximumSize(QSize(5242, 5242))
        self.value3_Slider.setFocusPolicy(Qt.ClickFocus)
        self.value3_Slider.setMaximum(255)
        self.value3_Slider.setOrientation(Qt.Horizontal)

        self.sliders_QVBoxLayout.addWidget(self.value3_Slider)


        self.horizontalLayout_11.addLayout(self.sliders_QVBoxLayout)

        self.horizontalLayout_11.setStretch(0, 1)

        self.horizontalLayout_2.addLayout(self.horizontalLayout_11)

        self.values_QVBoxLayout = QVBoxLayout()
        self.values_QVBoxLayout.setSpacing(6)
        self.values_QVBoxLayout.setObjectName(u"values_QVBoxLayout")
        self.values_QVBoxLayout.setSizeConstraint(QLayout.SetMinimumSize)
        self.values_QVBoxLayout.setContentsMargins(-1, 3, -1, -1)
        self.Value1_LineEdit = QLineEdit(self.sheetProcess_DockWidgetContents)
        self.Value1_LineEdit.setObjectName(u"Value1_LineEdit")
        self.Value1_LineEdit.setMaximumSize(QSize(60, 30))
        font2 = QFont()
        font2.setPointSize(18)
        self.Value1_LineEdit.setFont(font2)
        self.Value1_LineEdit.setFocusPolicy(Qt.ClickFocus)
        self.Value1_LineEdit.setMaxLength(32767)
        self.Value1_LineEdit.setAlignment(Qt.AlignCenter)

        self.values_QVBoxLayout.addWidget(self.Value1_LineEdit, 0, Qt.AlignRight)

        self.Value2_LineEdit = QLineEdit(self.sheetProcess_DockWidgetContents)
        self.Value2_LineEdit.setObjectName(u"Value2_LineEdit")
        self.Value2_LineEdit.setMaximumSize(QSize(60, 30))
        self.Value2_LineEdit.setFont(font2)
        self.Value2_LineEdit.setFocusPolicy(Qt.ClickFocus)
        self.Value2_LineEdit.setAlignment(Qt.AlignCenter)

        self.values_QVBoxLayout.addWidget(self.Value2_LineEdit, 0, Qt.AlignRight)

        self.Value3_LineEdit = QLineEdit(self.sheetProcess_DockWidgetContents)
        self.Value3_LineEdit.setObjectName(u"Value3_LineEdit")
        self.Value3_LineEdit.setMaximumSize(QSize(60, 30))
        self.Value3_LineEdit.setFont(font2)
        self.Value3_LineEdit.setFocusPolicy(Qt.ClickFocus)
        self.Value3_LineEdit.setAlignment(Qt.AlignCenter)

        self.values_QVBoxLayout.addWidget(self.Value3_LineEdit)


        self.horizontalLayout_2.addLayout(self.values_QVBoxLayout)

        self.process_Button_QVBoxLayout = QVBoxLayout()
        self.process_Button_QVBoxLayout.setSpacing(2)
        self.process_Button_QVBoxLayout.setObjectName(u"process_Button_QVBoxLayout")
        self.auto_Button = Custom_Button(self.sheetProcess_DockWidgetContents)
        self.auto_Button.setObjectName(u"auto_Button")
        self.auto_Button.setMinimumSize(QSize(111, 30))
        self.auto_Button.setFocusPolicy(Qt.ClickFocus)

        self.process_Button_QVBoxLayout.addWidget(self.auto_Button)

        self.manual_Button = Custom_Button(self.sheetProcess_DockWidgetContents)
        self.manual_Button.setObjectName(u"manual_Button")
        self.manual_Button.setMinimumSize(QSize(111, 30))
        self.manual_Button.setFocusPolicy(Qt.ClickFocus)

        self.process_Button_QVBoxLayout.addWidget(self.manual_Button)

        self.test_Button = Custom_Button(self.sheetProcess_DockWidgetContents)
        self.test_Button.setObjectName(u"test_Button")
        self.test_Button.setMinimumSize(QSize(111, 30))
        self.test_Button.setFocusPolicy(Qt.ClickFocus)

        self.process_Button_QVBoxLayout.addWidget(self.test_Button)


        self.horizontalLayout_2.addLayout(self.process_Button_QVBoxLayout)

        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setVerticalSpacing(2)
        self.gausMedian_RadioButton = QRadioButton(self.sheetProcess_DockWidgetContents)
        self.gausMedian_RadioButton.setObjectName(u"gausMedian_RadioButton")
        self.gausMedian_RadioButton.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_2.addWidget(self.gausMedian_RadioButton, 2, 0, 1, 1)

        self.sChanel_RadioButton = QRadioButton(self.sheetProcess_DockWidgetContents)
        self.sChanel_RadioButton.setObjectName(u"sChanel_RadioButton")
        self.sChanel_RadioButton.setFocusPolicy(Qt.ClickFocus)
        self.sChanel_RadioButton.setChecked(True)

        self.gridLayout_2.addWidget(self.sChanel_RadioButton, 0, 0, 1, 1)

        self.labChanel_RadioButton = QRadioButton(self.sheetProcess_DockWidgetContents)
        self.labChanel_RadioButton.setObjectName(u"labChanel_RadioButton")
        self.labChanel_RadioButton.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_2.addWidget(self.labChanel_RadioButton, 1, 0, 1, 1)

        self.imageCheck_Button = QPushButton(self.sheetProcess_DockWidgetContents)
        self.imageCheck_Button.setObjectName(u"imageCheck_Button")
        self.imageCheck_Button.setFocusPolicy(Qt.ClickFocus)
        self.imageCheck_Button.setCheckable(True)

        self.gridLayout_2.addWidget(self.imageCheck_Button, 3, 0, 1, 1)


        self.horizontalLayout_2.addLayout(self.gridLayout_2)

        self.horizontalLayout_2.setStretch(1, 10)
        self.sheetProcess_DockWidget.setWidget(self.sheetProcess_DockWidgetContents)
        MainWindow.addDockWidget(Qt.RightDockWidgetArea, self.sheetProcess_DockWidget)
        self.accounting_DockWidget = QDockWidget(MainWindow)
        self.accounting_DockWidget.setObjectName(u"accounting_DockWidget")
        self.accounting_DockWidget.setMinimumSize(QSize(670, 340))
        self.accounting_DockWidget.setMaximumSize(QSize(670, 340))
        self.accounting_DockWidget.setBaseSize(QSize(670, 340))
        self.accounting_DockWidget.setFont(font)
        self.accounting_DockWidget.setFocusPolicy(Qt.ClickFocus)
        self.accounting_DockWidget.setAllowedAreas(Qt.AllDockWidgetAreas)
        self.accounting_DockWidgetContents = QWidget()
        self.accounting_DockWidgetContents.setObjectName(u"accounting_DockWidgetContents")
        self.progressBar = QProgressBar(self.accounting_DockWidgetContents)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(660, 120, 414, 20))
        sizePolicy3.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy3)
        self.progressBar.setMinimumSize(QSize(414, 0))
        self.progressBar.setFocusPolicy(Qt.ClickFocus)
        self.progressBar.setMinimum(1)
        self.progressBar.setMaximum(1)
        self.progressBar.setValue(0)
        self.progressBar.setAlignment(Qt.AlignCenter)
        self.frame_2 = QFrame(self.accounting_DockWidgetContents)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(300, 255, 361, 61))
        self.frame_2.setMaximumSize(QSize(16777215, 61))
        self.frame_2.setFocusPolicy(Qt.ClickFocus)
        self.frame_2.setFrameShape(QFrame.NoFrame)
        self.frame_2.setFrameShadow(QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.procTest_Button = Custom_Button(self.frame_2)
        self.procTest_Button.setObjectName(u"procTest_Button")
        self.procTest_Button.setGeometry(QRect(300, 0, 60, 30))
        sizePolicy3.setHeightForWidth(self.procTest_Button.sizePolicy().hasHeightForWidth())
        self.procTest_Button.setSizePolicy(sizePolicy3)
        self.procTest_Button.setMinimumSize(QSize(60, 30))
        self.procTest_Button.setMaximumSize(QSize(60, 16777215))
        self.procTest_Button.setFocusPolicy(Qt.ClickFocus)
        self.addSupplyer_Button = Custom_Button(self.frame_2)
        self.addSupplyer_Button.setObjectName(u"addSupplyer_Button")
        self.addSupplyer_Button.setGeometry(QRect(0, 30, 100, 30))
        sizePolicy3.setHeightForWidth(self.addSupplyer_Button.sizePolicy().hasHeightForWidth())
        self.addSupplyer_Button.setSizePolicy(sizePolicy3)
        self.addSupplyer_Button.setMinimumSize(QSize(100, 30))
        self.addSupplyer_Button.setMaximumSize(QSize(100, 16777215))
        self.addSupplyer_Button.setFocusPolicy(Qt.ClickFocus)
        self.debug_Mode_Button = QPushButton(self.frame_2)
        self.debug_Mode_Button.setObjectName(u"debug_Mode_Button")
        self.debug_Mode_Button.setGeometry(QRect(300, 30, 60, 30))
        self.debug_Mode_Button.setMinimumSize(QSize(60, 30))
        self.debug_Mode_Button.setMaximumSize(QSize(50, 16777215))
        self.debug_Mode_Button.setFocusPolicy(Qt.ClickFocus)
        self.debug_Mode_Button.setCheckable(True)
        self.editSupplyer_Button = Custom_Button(self.frame_2)
        self.editSupplyer_Button.setObjectName(u"editSupplyer_Button")
        self.editSupplyer_Button.setGeometry(QRect(100, 30, 100, 30))
        sizePolicy3.setHeightForWidth(self.editSupplyer_Button.sizePolicy().hasHeightForWidth())
        self.editSupplyer_Button.setSizePolicy(sizePolicy3)
        self.editSupplyer_Button.setMinimumSize(QSize(100, 30))
        self.editSupplyer_Button.setMaximumSize(QSize(100, 16777215))
        self.editSupplyer_Button.setFocusPolicy(Qt.ClickFocus)
        self.OcrOnly_Button = Custom_Button(self.frame_2)
        self.OcrOnly_Button.setObjectName(u"OcrOnly_Button")
        self.OcrOnly_Button.setGeometry(QRect(200, 30, 100, 30))
        sizePolicy3.setHeightForWidth(self.OcrOnly_Button.sizePolicy().hasHeightForWidth())
        self.OcrOnly_Button.setSizePolicy(sizePolicy3)
        self.OcrOnly_Button.setMinimumSize(QSize(100, 30))
        self.OcrOnly_Button.setMaximumSize(QSize(100, 16777215))
        self.OcrOnly_Button.setFocusPolicy(Qt.ClickFocus)
        self.OCR_Tesseract_CheckBox = QCheckBox(self.frame_2)
        self.OCR_Tesseract_CheckBox.setObjectName(u"OCR_Tesseract_CheckBox")
        self.OCR_Tesseract_CheckBox.setGeometry(QRect(200, 5, 101, 22))
        self.verticalLayoutWidget = QWidget(self.accounting_DockWidgetContents)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(0, 200, 401, 53))
        self.verticalLayoutWidget.setFocusPolicy(Qt.ClickFocus)
        self.receiptEditor_QVBoxLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.receiptEditor_QVBoxLayout.setSpacing(0)
        self.receiptEditor_QVBoxLayout.setObjectName(u"receiptEditor_QVBoxLayout")
        self.receiptEditor_QVBoxLayout.setContentsMargins(0, 0, 0, 0)
        self.accLabels = QHBoxLayout()
        self.accLabels.setSpacing(0)
        self.accLabels.setObjectName(u"accLabels")
        self.category_Label = QLabel(self.verticalLayoutWidget)
        self.category_Label.setObjectName(u"category_Label")
        self.category_Label.setMinimumSize(QSize(120, 0))
        self.category_Label.setMaximumSize(QSize(120, 20))
        self.category_Label.setFocusPolicy(Qt.ClickFocus)
        self.category_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.category_Label.setIndent(5)

        self.accLabels.addWidget(self.category_Label)

        self.Supplyer_Label = QLabel(self.verticalLayoutWidget)
        self.Supplyer_Label.setObjectName(u"Supplyer_Label")
        self.Supplyer_Label.setMinimumSize(QSize(120, 0))
        self.Supplyer_Label.setMaximumSize(QSize(120, 20))
        self.Supplyer_Label.setFocusPolicy(Qt.ClickFocus)
        self.Supplyer_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.Supplyer_Label.setIndent(5)

        self.accLabels.addWidget(self.Supplyer_Label)

        self.amount_Label = QLabel(self.verticalLayoutWidget)
        self.amount_Label.setObjectName(u"amount_Label")
        self.amount_Label.setMinimumSize(QSize(120, 0))
        self.amount_Label.setMaximumSize(QSize(120, 20))
        self.amount_Label.setFocusPolicy(Qt.ClickFocus)
        self.amount_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.amount_Label.setIndent(5)

        self.accLabels.addWidget(self.amount_Label)


        self.receiptEditor_QVBoxLayout.addLayout(self.accLabels)

        self.receiptEditorBox = QGridLayout()
        self.receiptEditorBox.setObjectName(u"receiptEditorBox")
        self.receiptEditorBox.setContentsMargins(-1, 0, -1, 0)
        self.category_ComboBox = Custom_ComboBox(self.verticalLayoutWidget)
        self.category_ComboBox.addItem("")
        self.category_ComboBox.addItem("")
        self.category_ComboBox.addItem("")
        self.category_ComboBox.addItem("")
        self.category_ComboBox.addItem("")
        self.category_ComboBox.setObjectName(u"category_ComboBox")
        self.category_ComboBox.setMinimumSize(QSize(120, 27))
        self.category_ComboBox.setMaximumSize(QSize(115, 25))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(True)
        self.category_ComboBox.setFont(font3)
        self.category_ComboBox.setFocusPolicy(Qt.StrongFocus)

        self.receiptEditorBox.addWidget(self.category_ComboBox, 0, 0, 1, 1)

        self.supplyerComboBox = Custom_ComboBox(self.verticalLayoutWidget)
        self.supplyerComboBox.setObjectName(u"supplyerComboBox")
        sizePolicy6 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.supplyerComboBox.sizePolicy().hasHeightForWidth())
        self.supplyerComboBox.setSizePolicy(sizePolicy6)
        self.supplyerComboBox.setMinimumSize(QSize(120, 27))
        self.supplyerComboBox.setMaximumSize(QSize(115, 25))
        self.supplyerComboBox.setFont(font3)
        self.supplyerComboBox.setFocusPolicy(Qt.StrongFocus)
        self.supplyerComboBox.setEditable(False)
        self.supplyerComboBox.setFrame(False)
        self.supplyerComboBox.setModelColumn(0)

        self.receiptEditorBox.addWidget(self.supplyerComboBox, 0, 1, 1, 1)

        self.amount_LineEdit = Custom_LineEdit(self.verticalLayoutWidget)
        self.amount_LineEdit.setObjectName(u"amount_LineEdit")
        sizePolicy6.setHeightForWidth(self.amount_LineEdit.sizePolicy().hasHeightForWidth())
        self.amount_LineEdit.setSizePolicy(sizePolicy6)
        self.amount_LineEdit.setMinimumSize(QSize(120, 27))
        self.amount_LineEdit.setMaximumSize(QSize(115, 25))
        font4 = QFont()
        font4.setPointSize(13)
        font4.setBold(True)
        self.amount_LineEdit.setFont(font4)
        self.amount_LineEdit.setFocusPolicy(Qt.StrongFocus)
        self.amount_LineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.receiptEditorBox.addWidget(self.amount_LineEdit, 0, 2, 1, 1)


        self.receiptEditor_QVBoxLayout.addLayout(self.receiptEditorBox)

        self.gridLayoutWidget_3 = QWidget(self.accounting_DockWidgetContents)
        self.gridLayoutWidget_3.setObjectName(u"gridLayoutWidget_3")
        self.gridLayoutWidget_3.setGeometry(QRect(0, 254, 402, 32))
        self.gridLayoutWidget_3.setFocusPolicy(Qt.ClickFocus)
        self.category_Buttons = QGridLayout(self.gridLayoutWidget_3)
        self.category_Buttons.setObjectName(u"category_Buttons")
        self.category_Buttons.setHorizontalSpacing(0)
        self.category_Buttons.setContentsMargins(0, 0, 0, 0)
        self.food_Button = Custom_Button(self.gridLayoutWidget_3)
        self.food_Button.setObjectName(u"food_Button")
        sizePolicy3.setHeightForWidth(self.food_Button.sizePolicy().hasHeightForWidth())
        self.food_Button.setSizePolicy(sizePolicy3)
        self.food_Button.setMinimumSize(QSize(100, 30))
        self.food_Button.setMaximumSize(QSize(100, 16777215))
        self.food_Button.setFocusPolicy(Qt.ClickFocus)

        self.category_Buttons.addWidget(self.food_Button, 0, 0, 1, 1)

        self.Petrol_Button = Custom_Button(self.gridLayoutWidget_3)
        self.Petrol_Button.setObjectName(u"Petrol_Button")
        sizePolicy3.setHeightForWidth(self.Petrol_Button.sizePolicy().hasHeightForWidth())
        self.Petrol_Button.setSizePolicy(sizePolicy3)
        self.Petrol_Button.setMinimumSize(QSize(100, 30))
        self.Petrol_Button.setMaximumSize(QSize(100, 16777215))
        self.Petrol_Button.setFocusPolicy(Qt.ClickFocus)

        self.category_Buttons.addWidget(self.Petrol_Button, 0, 2, 1, 1)

        self.supply_Button = Custom_Button(self.gridLayoutWidget_3)
        self.supply_Button.setObjectName(u"supply_Button")
        sizePolicy3.setHeightForWidth(self.supply_Button.sizePolicy().hasHeightForWidth())
        self.supply_Button.setSizePolicy(sizePolicy3)
        self.supply_Button.setMinimumSize(QSize(100, 30))
        self.supply_Button.setMaximumSize(QSize(100, 16777215))
        self.supply_Button.setFocusPolicy(Qt.ClickFocus)

        self.category_Buttons.addWidget(self.supply_Button, 0, 1, 1, 1)

        self.other_Button = Custom_Button(self.gridLayoutWidget_3)
        self.other_Button.setObjectName(u"other_Button")
        sizePolicy3.setHeightForWidth(self.other_Button.sizePolicy().hasHeightForWidth())
        self.other_Button.setSizePolicy(sizePolicy3)
        self.other_Button.setMinimumSize(QSize(100, 30))
        self.other_Button.setMaximumSize(QSize(100, 16777215))
        self.other_Button.setFocusPolicy(Qt.ClickFocus)

        self.category_Buttons.addWidget(self.other_Button, 0, 3, 1, 1)

        self.gridLayoutWidget_4 = QWidget(self.accounting_DockWidgetContents)
        self.gridLayoutWidget_4.setObjectName(u"gridLayoutWidget_4")
        self.gridLayoutWidget_4.setGeometry(QRect(0, 284, 302, 32))
        self.gridLayoutWidget_4.setFocusPolicy(Qt.ClickFocus)
        self.add_del_Buttons = QGridLayout(self.gridLayoutWidget_4)
        self.add_del_Buttons.setObjectName(u"add_del_Buttons")
        self.add_del_Buttons.setHorizontalSpacing(0)
        self.add_del_Buttons.setContentsMargins(0, 0, 0, 0)
        self.delReceipt_Button = Custom_Button(self.gridLayoutWidget_4)
        self.delReceipt_Button.setObjectName(u"delReceipt_Button")
        sizePolicy3.setHeightForWidth(self.delReceipt_Button.sizePolicy().hasHeightForWidth())
        self.delReceipt_Button.setSizePolicy(sizePolicy3)
        self.delReceipt_Button.setMinimumSize(QSize(100, 30))
        self.delReceipt_Button.setMaximumSize(QSize(100, 16777215))
        self.delReceipt_Button.setFocusPolicy(Qt.ClickFocus)

        self.add_del_Buttons.addWidget(self.delReceipt_Button, 0, 1, 1, 1)

        self.add_Button = Custom_Button(self.gridLayoutWidget_4)
        self.add_Button.setObjectName(u"add_Button")
        sizePolicy3.setHeightForWidth(self.add_Button.sizePolicy().hasHeightForWidth())
        self.add_Button.setSizePolicy(sizePolicy3)
        self.add_Button.setMinimumSize(QSize(100, 30))
        self.add_Button.setMaximumSize(QSize(100, 16777215))
        self.add_Button.setFocusPolicy(Qt.ClickFocus)

        self.add_del_Buttons.addWidget(self.add_Button, 0, 0, 1, 1)

        self.update_Button = Custom_Button(self.gridLayoutWidget_4)
        self.update_Button.setObjectName(u"update_Button")
        sizePolicy3.setHeightForWidth(self.update_Button.sizePolicy().hasHeightForWidth())
        self.update_Button.setSizePolicy(sizePolicy3)
        self.update_Button.setMinimumSize(QSize(100, 30))
        self.update_Button.setMaximumSize(QSize(100, 16777215))
        self.update_Button.setFocusPolicy(Qt.ClickFocus)

        self.add_del_Buttons.addWidget(self.update_Button, 0, 2, 1, 1)

        self.verticalLayoutWidget_2 = QWidget(self.accounting_DockWidgetContents)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(0, 0, 671, 202))
        self.verticalLayoutWidget_2.setFocusPolicy(Qt.ClickFocus)
        self.receiptList_Layout = QHBoxLayout(self.verticalLayoutWidget_2)
        self.receiptList_Layout.setSpacing(13)
        self.receiptList_Layout.setObjectName(u"receiptList_Layout")
        self.receiptList_Layout.setContentsMargins(0, 0, 0, 0)
        self.receiptList_TreeView = QTreeView(self.verticalLayoutWidget_2)
        self.receiptList_TreeView.setObjectName(u"receiptList_TreeView")
        sizePolicy6.setHeightForWidth(self.receiptList_TreeView.sizePolicy().hasHeightForWidth())
        self.receiptList_TreeView.setSizePolicy(sizePolicy6)
        self.receiptList_TreeView.setMinimumSize(QSize(400, 200))
        self.receiptList_TreeView.setMaximumSize(QSize(400, 200))
        self.receiptList_TreeView.setMouseTracking(True)
        self.receiptList_TreeView.setTabletTracking(True)
        self.receiptList_TreeView.setFocusPolicy(Qt.StrongFocus)
        self.receiptList_TreeView.setStyleSheet(u"")
        self.receiptList_TreeView.setAlternatingRowColors(False)
        self.receiptList_TreeView.setIndentation(5)
        self.receiptList_TreeView.setItemsExpandable(False)
        self.receiptList_TreeView.setAllColumnsShowFocus(True)
        self.receiptList_TreeView.header().setStretchLastSection(False)

        self.receiptList_Layout.addWidget(self.receiptList_TreeView)

        self.calendarWidget = QCalendarWidget(self.verticalLayoutWidget_2)
        self.calendarWidget.setObjectName(u"calendarWidget")
        sizePolicy2.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy2)
        self.calendarWidget.setMinimumSize(QSize(240, 200))
        self.calendarWidget.setMaximumSize(QSize(240, 200))
        self.calendarWidget.setFont(font)
        self.calendarWidget.setFocusPolicy(Qt.ClickFocus)
        self.calendarWidget.setAutoFillBackground(False)
        self.calendarWidget.setStyleSheet(u"")
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setVerticalHeaderFormat(QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)

        self.receiptList_Layout.addWidget(self.calendarWidget)

        self.formLayoutWidget = QWidget(self.accounting_DockWidgetContents)
        self.formLayoutWidget.setObjectName(u"formLayoutWidget")
        self.formLayoutWidget.setGeometry(QRect(500, 210, 175, 31))
        self.formLayoutWidget.setFocusPolicy(Qt.ClickFocus)
        self.Date_Layout = QFormLayout(self.formLayoutWidget)
        self.Date_Layout.setObjectName(u"Date_Layout")
        self.Date_Layout.setHorizontalSpacing(5)
        self.Date_Layout.setVerticalSpacing(0)
        self.Date_Layout.setContentsMargins(0, 0, 0, 0)
        self.date_Label = QLabel(self.formLayoutWidget)
        self.date_Label.setObjectName(u"date_Label")
        self.date_Label.setMinimumSize(QSize(42, 25))
        self.date_Label.setMaximumSize(QSize(31, 16))
        self.date_Label.setFocusPolicy(Qt.ClickFocus)
        self.date_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.date_Label.setIndent(5)

        self.Date_Layout.setWidget(0, QFormLayout.LabelRole, self.date_Label)

        self.date_lineEdit = Custom_LineEdit(self.formLayoutWidget)
        self.date_lineEdit.setObjectName(u"date_lineEdit")
        sizePolicy6.setHeightForWidth(self.date_lineEdit.sizePolicy().hasHeightForWidth())
        self.date_lineEdit.setSizePolicy(sizePolicy6)
        self.date_lineEdit.setMinimumSize(QSize(117, 27))
        self.date_lineEdit.setMaximumSize(QSize(117, 25))
        self.date_lineEdit.setFocusPolicy(Qt.StrongFocus)
        self.date_lineEdit.setAlignment(Qt.AlignCenter)

        self.Date_Layout.setWidget(0, QFormLayout.FieldRole, self.date_lineEdit)

        self.gridLayoutWidget_5 = QWidget(self.accounting_DockWidgetContents)
        self.gridLayoutWidget_5.setObjectName(u"gridLayoutWidget_5")
        self.gridLayoutWidget_5.setGeometry(QRect(400, 210, 102, 62))
        self.gridLayoutWidget_5.setFocusPolicy(Qt.ClickFocus)
        self.save_Buttons = QGridLayout(self.gridLayoutWidget_5)
        self.save_Buttons.setSpacing(0)
        self.save_Buttons.setObjectName(u"save_Buttons")
        self.save_Buttons.setContentsMargins(0, 0, 0, 0)
        self.saveNew_Button = Custom_Button(self.gridLayoutWidget_5)
        self.saveNew_Button.setObjectName(u"saveNew_Button")
        sizePolicy3.setHeightForWidth(self.saveNew_Button.sizePolicy().hasHeightForWidth())
        self.saveNew_Button.setSizePolicy(sizePolicy3)
        self.saveNew_Button.setMinimumSize(QSize(80, 30))
        self.saveNew_Button.setMaximumSize(QSize(80, 16777215))
        self.saveNew_Button.setFocusPolicy(Qt.StrongFocus)
        self.saveNew_Button.setAutoDefault(True)

        self.save_Buttons.addWidget(self.saveNew_Button, 1, 0, 1, 1)

        self.save_Button = Custom_Button(self.gridLayoutWidget_5)
        self.save_Button.setObjectName(u"save_Button")
        sizePolicy3.setHeightForWidth(self.save_Button.sizePolicy().hasHeightForWidth())
        self.save_Button.setSizePolicy(sizePolicy3)
        self.save_Button.setMinimumSize(QSize(80, 30))
        self.save_Button.setMaximumSize(QSize(80, 16777215))
        self.save_Button.setFocusPolicy(Qt.StrongFocus)
        self.save_Button.setAutoDefault(True)

        self.save_Buttons.addWidget(self.save_Button, 0, 0, 1, 1)

        self.accounting_DockWidget.setWidget(self.accounting_DockWidgetContents)
        MainWindow.addDockWidget(Qt.RightDockWidgetArea, self.accounting_DockWidget)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.ocrText_DockWidget = QDockWidget(MainWindow)
        self.ocrText_DockWidget.setObjectName(u"ocrText_DockWidget")
        self.ocrText_DockWidget.setMinimumSize(QSize(250, 182))
        self.ocrText_DockWidget.setFocusPolicy(Qt.ClickFocus)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.horizontalLayout = QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.ocrString_textBrowser = QTextBrowser(self.dockWidgetContents)
        self.ocrString_textBrowser.setObjectName(u"ocrString_textBrowser")
        sizePolicy.setHeightForWidth(self.ocrString_textBrowser.sizePolicy().hasHeightForWidth())
        self.ocrString_textBrowser.setSizePolicy(sizePolicy)
        self.ocrString_textBrowser.setMinimumSize(QSize(250, 0))
        self.ocrString_textBrowser.setMaximumSize(QSize(16777215, 16777215))
        self.ocrString_textBrowser.setFocusPolicy(Qt.ClickFocus)

        self.horizontalLayout.addWidget(self.ocrString_textBrowser)

        self.ocrText_DockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.LeftDockWidgetArea, self.ocrText_DockWidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1470, 21))
        self.menuEdit = QMenu(self.menuBar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuView = QMenu(self.menuBar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menuBar)
#if QT_CONFIG(shortcut)
        self.category_Label.setBuddy(self.category_ComboBox)
        self.Supplyer_Label.setBuddy(self.supplyerComboBox)
        self.amount_Label.setBuddy(self.amount_LineEdit)
#endif // QT_CONFIG(shortcut)
        QWidget.setTabOrder(self.amount_LineEdit, self.save_Button)
        QWidget.setTabOrder(self.save_Button, self.saveNew_Button)
        QWidget.setTabOrder(self.saveNew_Button, self.date_lineEdit)
        QWidget.setTabOrder(self.date_lineEdit, self.receiptList_TreeView)
        QWidget.setTabOrder(self.receiptList_TreeView, self.category_ComboBox)
        QWidget.setTabOrder(self.category_ComboBox, self.supplyerComboBox)

        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionFile_F.setText(QCoreApplication.translate("MainWindow", u"File(F)", None))
        self.action_Save.setText(QCoreApplication.translate("MainWindow", u"&Save", None))
        self.fileList_DockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u30d5\u30a1\u30a4\u30eb\u30ea\u30b9\u30c8", None))
        self.folderSelect_Button.setText(QCoreApplication.translate("MainWindow", u"Folder Select", None))
        self.deleteFile_Button.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.makeCSV_Button.setText(QCoreApplication.translate("MainWindow", u"Make CSV", None))
        self.prevSheet_Button.setText(QCoreApplication.translate("MainWindow", u"Prev Sheet", None))
        self.nextSheet_Button.setText(QCoreApplication.translate("MainWindow", u"Next Seet", None))
        self.receiptImage_DockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u30ec\u30b7\u30fc\u30c8\u753b\u50cf", None))
        self.prevReceipt_Button.setText(QCoreApplication.translate("MainWindow", u"<< Prev", None))
        self.reOcr_Button.setText(QCoreApplication.translate("MainWindow", u"OCR", None))
        self.nextReceipt_Button.setText(QCoreApplication.translate("MainWindow", u"Next >>", None))
        self.sheetProcess_DockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u53d6\u8fbc\u51e6\u7406", None))
        self.standerd_Button.setText(QCoreApplication.translate("MainWindow", u"Standerd", None))
        self.mideum_Button.setText(QCoreApplication.translate("MainWindow", u"Medium", None))
        self.lite_Button.setText(QCoreApplication.translate("MainWindow", u"Lite", None))
        self.value1_Label.setText(QCoreApplication.translate("MainWindow", u"Value 1", None))
        self.value2_Label.setText(QCoreApplication.translate("MainWindow", u"Value 2", None))
        self.value3_Label.setText(QCoreApplication.translate("MainWindow", u"Value 3", None))
        self.Value1_LineEdit.setInputMask("")
        self.Value1_LineEdit.setText("")
        self.Value2_LineEdit.setInputMask("")
        self.Value2_LineEdit.setText("")
        self.Value3_LineEdit.setInputMask("")
        self.Value3_LineEdit.setText("")
        self.auto_Button.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
        self.manual_Button.setText(QCoreApplication.translate("MainWindow", u"Manual", None))
        self.test_Button.setText(QCoreApplication.translate("MainWindow", u"Test", None))
        self.gausMedian_RadioButton.setText(QCoreApplication.translate("MainWindow", u"Gaus-Median", None))
        self.sChanel_RadioButton.setText(QCoreApplication.translate("MainWindow", u"S Chanel", None))
        self.labChanel_RadioButton.setText(QCoreApplication.translate("MainWindow", u"LAB Chanel", None))
        self.imageCheck_Button.setText(QCoreApplication.translate("MainWindow", u"\u6700\u7d42\u51e6\u7406\u753b\u50cf", None))
        self.accounting_DockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u8a18\u5e33", None))
        self.progressBar.setFormat(QCoreApplication.translate("MainWindow", u"%v/%m", None))
        self.procTest_Button.setText(QCoreApplication.translate("MainWindow", u"Proc Test", None))
        self.addSupplyer_Button.setText(QCoreApplication.translate("MainWindow", u"Add Suplyer", None))
        self.debug_Mode_Button.setText(QCoreApplication.translate("MainWindow", u"Debug", None))
        self.editSupplyer_Button.setText(QCoreApplication.translate("MainWindow", u"Edit Suplyer", None))
        self.OcrOnly_Button.setText(QCoreApplication.translate("MainWindow", u"OCR Only", None))
        self.OCR_Tesseract_CheckBox.setText(QCoreApplication.translate("MainWindow", u"Tesseract OCR", None))
        self.category_Label.setText(QCoreApplication.translate("MainWindow", u"\u9069\u3000\u7528 (&D)", None))
        self.Supplyer_Label.setText(QCoreApplication.translate("MainWindow", u"\u5e97\u3000\u540d (&S)", None))
        self.amount_Label.setText(QCoreApplication.translate("MainWindow", u"\u91d1\u3000\u984d (&/)", None))
        self.category_ComboBox.setItemText(0, "")
        self.category_ComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"\u98df\u6750\u6599\u8cbb", None))
        self.category_ComboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"\u65e5\u7528\u54c1\u8cbb", None))
        self.category_ComboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"\u30ac\u30bd\u30ea\u30f3\u4ee3", None))
        self.category_ComboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"\u305d\u306e\u4ed6", None))

        self.supplyerComboBox.setCurrentText("")
        self.supplyerComboBox.setPlaceholderText("")
        self.amount_LineEdit.setInputMask("")
        self.amount_LineEdit.setText("")
        self.food_Button.setText(QCoreApplication.translate("MainWindow", u"\u98df\u6750\u6599\u8cbb (&0)", None))
        self.Petrol_Button.setText(QCoreApplication.translate("MainWindow", u"\u30ac\u30bd\u30ea\u30f3\u4ee3 (&2)", None))
        self.supply_Button.setText(QCoreApplication.translate("MainWindow", u"\u65e5\u7528\u54c1\u8cbb (&1)", None))
        self.other_Button.setText(QCoreApplication.translate("MainWindow", u"\u305d\u306e\u4ed6 (&3)", None))
        self.delReceipt_Button.setText(QCoreApplication.translate("MainWindow", u"Delete (Ctrl+Del)", None))
        self.add_Button.setText(QCoreApplication.translate("MainWindow", u"&Add", None))
        self.update_Button.setText(QCoreApplication.translate("MainWindow", u"&Update", None))
        self.date_Label.setText(QCoreApplication.translate("MainWindow", u"\u65e5\u3000\u4ed8", None))
#if QT_CONFIG(tooltip)
        self.saveNew_Button.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(tooltip)
        self.saveNew_Button.setText(QCoreApplication.translate("MainWindow", u"Save New", None))
#if QT_CONFIG(tooltip)
        self.save_Button.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(tooltip)
        self.save_Button.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.ocrText_DockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"OCR Text", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"&Edit", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"&View", None))
    # retranslateUi

